### ISSUE TITLE
Add Internal Exchange Rates

### ISSUE THREAD

**Issue by OdinsPlasmaRifle** [rehive/service-ico#1]
Add functionality to add Rates for each phase of an ICO.

The adding of rates should work as follows: Create a rate object for each company currency and phase. These rates need to be calculated based on the ICOs `fiat_currency` and the `fiat_rate` for the specific phase. A default internal exchange provider needs to be chosen for this, the provider should cover all national currencies as well as primary crypto currencies (and all crypto currencies offered by Rehive, eg XBT, ETH, XLM). Rates are internal only, they should be exposed by a GET request in the API (done already) but should not be available for update by any permission level.

The following needs to be taken into account: 

1) The rates should be added n phase creation. Whenever a phase is created rates should be auto created.

2) The rates should be updated once every X minutes (10 minutes). You can deal with this last, we will probs use a scheduler for this.

3) There needs to be an easy way to get an updated set of rates for a specific currency. This is needed in some cases in the quite logic.

4) The rates need to be updated across multiple companies, phases and currencies.\

Take a look here for an overview of the ICO specifications: https://docs.google.com/document/d/12krl5rCCJS144UahSn-U7Xc2nEdCdzaYqhirP1uvd3E/edit. However, consider stuff already done in the code as the "canonical" way of doing things. The specification is flexible in terms of backend logic.

Please let me know if you have any further questions.

**Comment by crintus** [comment]
Merged into master
