### ISSUE TITLE
Improve Service Serializers/Standardize Data

### ISSUE THREAD

**Issue by OdinsPlasmaRifle** [rehive/service-ico#3]
Can you please clean up the serializers on the ICO service. The following is a general list of what needs doing:

1. Add currency object serializer whenever an currency object is returned in GET (make sure POST still receives a CharField). This serializer should match the appearance of the Rehive one.
2. Make all serializers receive and output integers for MoneyFields. Decimal values should styill be stored and used for internal logic.
3. Update relevant serializers to include and `id` field (and check for other data that may be useful).
4. Add auto updating of cache when accessing rates model via `Rate.objects`
5. Add pagination for all listings.

Please feel free to make other improvements. The goal is to make the ICO service as similar to the Rehive "standard" structure as possible without adding bloat.

**Comment by crintus** [comment]
This has been merged into master
